name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up node using nvm
      uses: dcodeIO/setup-node-nvm@v2.0.0
    - run: npm install
    - run: npm test
      env:
        CI: true
